(source gnu)
(source melpa)

;; setup
(depends-on "init-loader")

;; default elisp
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-pos-tip")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "magit-gitflow")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; Added by me

;; ...
(depends-on "powerline")
(depends-on "smooth-scroll")

;; Manage window or workspace
(depends-on "persp-mode")

;; Auto completion
(depends-on "company")
(depends-on "auto-complete")

;; Japanese input
(depends-on "mozc")

;; Edit through ssh on Emacs
(depends-on "tramp")

;; undo and redo
(depends-on "undo-tree")

;; Hightlight parts related to a certain operation
(depends-on "volatile-highlights")

;; Each language mode
(depends-on "cmake-mode")
(depends-on "cc-mode")
(depends-on "mmm-mode")

;; Improve the editing experience for the c, c++
(depends-on "irony")
(depends-on "flycheck-irony")

;; Python auto-completion package for Emacs
(depends-on "jedi-core")
(depends-on "company-jedi")

;; Front-end for interacting with external debuggers
(depends-on "realgud")

;; Auto insert template 
(depends-on "autoinsert")

;; Edit multiple region
(depends-on "iedit")

;; Emacs framework for completions and selections
(depends-on "helm")
(depends-on "helm-company")
(depends-on "helm-flycheck")
(depends-on "helm-swoop")

;; Edit web browser input region by emacs directly
(depends-on "atomic-chrome")

;; color theme
(depends-on "atom-one-dark-theme")


;;markdown-mode
(depends-on "markdown-mode")

